name: ElytraRoofPatch
main: io.github.izdabait.rooflimiter.rooflimiter
version: 2.1.3
author: io.github.izdabait
description: A plugin made to patch people from flying too fast on the nether roof with the elytra.
commands:
  ep:
    description: Help or reload for ElytraRoofPatch
    aliases: elytrapatch, erp
    usage: /<command>